{{- $global_data := .Values.global }}
{{- if and (hasKey .Values "global") (hasKey .Values.global.control "simTeiSparse") (.Values.global.control.simTeiSparse.enabled) }}
{{- if $global_data.serviceMonitor -}}
{{- if $global_data.serviceMonitor.enabled -}}
apiVersion: {{ include "common.ServiceMonitor.apiVersion" . }}
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "sim-tei-sparse.labels" . | nindent 4 }}
    {{- include "common.ServiceMonitor.metadata.labes" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sim-tei-sparse.selectorLabels" . | nindent 6 }}
  endpoints:
  - path: {{ .Values.prometheusPath | default "/metrics" }}
    targetPort: http
    interval: {{ .Values.prometheusInterval | default "15s" }}
{{- end -}}
{{- end -}}
{{- end }}
