{{- if and (hasKey .Values "global") (hasKey .Values.global.control "simTeiSparse") (.Values.global.control.simTeiSparse.enabled) (.Values.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-serviceaccount
  labels:
    {{- include "sim-tei-sparse.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
